[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyvale"
version = "0.0.1"
description = "A python validation engine (pyvale)"
authors = [
  { name = "scepticalrabbit", email = "thescepticalrabbit@gmail.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: MIT",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = [
  "numpy>=1.26.0",
  "netCDF4>=1.6.5",
  "pyvista>=0.43.3",
  "matplotlib>=3.8",
  "scipy==1.11.3",
  "shapely>=2.0.4",
]

[project.urls]
"Repository" = "https://github.com/Applied-Materials-Technology/pyvale"
"Issue Tracker" = "https://github.com/Applied-Materials-Technology/pyvale/issues"

[tool.setuptools.packages.find]
where = ["src"]
