import numpy
from typing import overload

class BVH_node(Hittable):
    def __init__(self, arg0: Hittable_list) -> None: ...

class Box(Hittable):
    def __init__(self, arg0: vec3, arg1: vec3, arg2: Material) -> None: ...

class Camera:
    def __init__(self, arg0: vec3, arg1: vec3, arg2: float, arg3: float, arg4: float, arg5: float, arg6: vec3, arg7: int) -> None: ...

class Diffuse_light(Material):
    def __init__(self, arg0: texture) -> None: ...

class Hittable:
    def __init__(self, *args, **kwargs) -> None: ...

class Hittable_list:
    def __init__(self) -> None: ...
    def add(self, arg0: Hittable) -> None: ...

class Material:
    def __init__(self, *args, **kwargs) -> None: ...

class Plane_xy(Hittable):
    def __init__(self, x0: float, x1: float, y0: float, y1: float, z: float, Material: Material) -> None: ...

class Plane_xz(Hittable):
    def __init__(self, x0: float, x1: float, z0: float, z1: float, y: float, Material: Material) -> None: ...

class Plane_yz(Hittable):
    def __init__(self, y0: float, y1: float, z0: float, z1: float, x: float, Material: Material) -> None: ...

class Quad(Hittable):
    def __init__(self, Q: vec3, u: vec3, v: vec3, Material: Material) -> None: ...

class Rotate_y(Hittable):
    def __init__(self, arg0: Hittable, arg1: float) -> None: ...

class ShapeQuadLin(Hittable):
    def __init__(self, arg0: numpy.ndarray[numpy.float64[4, 3]], arg1: numpy.ndarray[numpy.float64[4, 3]], arg2: Material) -> None: ...

class ShapeQuadQuad(Hittable):
    def __init__(self, arg0: numpy.ndarray[numpy.float64[8, 3]], arg1: numpy.ndarray[numpy.float64[8, 3]], arg2: Material) -> None: ...

class Sphere(Hittable):
    def __init__(self, arg0: vec3, arg1: float, arg2: Material) -> None: ...

class Translate(Hittable):
    def __init__(self, arg0: Hittable, arg1: vec3) -> None: ...

class Tri(Hittable):
    def __init__(self, Q: vec3, u: vec3, v: vec3, Material: Material) -> None: ...

class checker_texture(texture):
    def __init__(self, arg0: solid_color, arg1: solid_color) -> None: ...

class solid_color(texture):
    @overload
    def __init__(self, arg0: vec3) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float) -> None: ...

class texture:
    def __init__(self, *args, **kwargs) -> None: ...

class vec3:
    def __init__(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def length(self) -> float: ...
    def __add__(self, arg0: vec3) -> vec3: ...
    def __iadd__(self, arg0: vec3) -> vec3: ...
    def __imul__(self, arg0: float) -> vec3: ...
    def __itruediv__(self, arg0: float) -> vec3: ...
    def __mul__(self, arg0: float) -> vec3: ...
    def __neg__(self) -> vec3: ...
    def __rmul__(self, arg0: float) -> vec3: ...
