# ==============================================================================
# pyvale: the python validation engine
# License: MIT
# Copyright (C) 2026 Sceptical Rabbit (Lloyd Fletcher)
# ==============================================================================
"""Unified rendering APIs for pyvale.

The namespace separates validated three-dimensional scene renderers from
validated planar image-warp renderers. The default 3D implementation is
:class:`Riley`; :class:`ImageDef2D` provides the initial 2D implementation.
"""

from .blender import (
    Blender,
    BlenderCalibrationData,
    BlenderCalibrationTarget,
    BlenderConfig,
    BlenderImageShader,
    BlenderMaterial,
    BlenderTextureShader,
    EBlenderDevice,
    EBlenderEngine,
    blender_available,
    blender_camera_from_resolution,
    blender_field_of_view,
    blender_gpu_available,
    blender_mm_per_pixel,
    calibration_image_count,
    focal_length_from_resolution,
    raise_if_blender_unavailable,
    render_calibration_images,
)
from .camera import Camera, Camera2D, EDistortionModel, EPSFType
from .cameratools import (
    StereoAngles,
    StereoCameras,
    StereoExtrinsics,
    average_subpixel_image,
    cam_frame_mesh,
    cam_frame_points,
    cam_frame_scene,
    cam_look_at,
    cam_pos_fill_frame,
    cam_project_points,
    crop_image_rectangle,
    pixel_grid_leng,
    pixel_vec_leng,
    subpixel_grid_leng,
    subpixel_vec_leng,
    stereo_build_faceon,
    stereo_build_from_calibration,
    stereo_build_symmetric,
    stereo_calc_angles,
    stereo_calc_baseline,
    stereo_calc_extrinsics,
    stereo_calc_stand_off,
    stereo_save_calibration_matchid,
    stereo_save_calibration_yaml,
)
from .capabilities import RenderCapabilities
from .errors import RenderInputError, ValidationIssue
from .feebee import (
    EFeebeeMaterialType,
    EFeebeeShading,
    EFeebeeTextureSampler,
    Feebee,
    FeebeeColourShader,
    FeebeeConfig,
    FeebeeMaterial,
    FeebeeTextureShader,
)
from .imagedef2d import ImageDef2D, ImageDefOpts
from .imagetools import (
    EImageType,
    image_crop,
    image_grayscale,
    image_load,
    image_normalise,
    image_resize,
    image_save,
)
from .imagewarp2d import IImageWarp2D
from .light import ELightType, Light
from .mesh import EElementType, Mesh2D, Mesh3D
from .meshtools import (
    evenly_spaced_frame_indices,
    first_last_frame_indices,
    mesh2d_from_simdata,
    mesh3d_from_simdata,
    mesh_bounds,
    mesh_center,
    mesh_center_at,
    mesh_rotate,
    mesh_scale,
    mesh_transform,
    mesh_translate,
    select_frames,
)
from .pxint2d import (
    AdditiveSpeckles,
    AnalyticRule,
    Eggbox,
    EPxIntMapping,
    GaussianPSF,
    GaussRule,
    PixIntGrid2D,
    PixIntSpeck2D,
    PxInt2DOpts,
    RectRule,
    quantise_image,
)
from .rasterops import (
    calculate_edge_function,
    calculate_elem_bound_box_high,
    calculate_elem_bound_box_low,
    format_image_number,
)
from .renderer3d import IRenderer3D
from .result import ImageWarpResult, RenderResult
from .riley import (
    Riley,
    RileyFunctionShader,
    RileyNodalShader,
    RileyTextureShader,
    to_riley_camera,
    to_riley_mesh,
)
from .scene import Scene2D, Scene3D
from .scenetools import (
    scene_arrange_circle,
    scene_arrange_grid,
    scene_arrange_line,
    scene_arrange_points,
    scene_bounds,
    scene_center,
    scene_rotate,
    scene_translate,
)
from .uvtools import (
    EUVFit,
    EUVOrigin,
    EUVPlane,
    UVPlane,
    UVTransform,
    uv_from_pixels,
    uv_project_planar,
    uv_project_planar_centered,
    uv_project_planar_pixels,
    uv_to_pixels,
    uv_transform,
)

__all__ = [
    "AdditiveSpeckles",
    "AnalyticRule",
    "Blender",
    "BlenderCalibrationData",
    "BlenderCalibrationTarget",
    "BlenderConfig",
    "BlenderImageShader",
    "BlenderMaterial",
    "BlenderTextureShader",
    "Camera",
    "Camera2D",
    "EBlenderDevice",
    "EBlenderEngine",
    "EDistortionModel",
    "EElementType",
    "EFeebeeMaterialType",
    "EFeebeeShading",
    "EFeebeeTextureSampler",
    "EImageType",
    "ELightType",
    "EPSFType",
    "EPxIntMapping",
    "EUVFit",
    "EUVOrigin",
    "EUVPlane",
    "Eggbox",
    "Feebee",
    "FeebeeColourShader",
    "FeebeeConfig",
    "FeebeeMaterial",
    "FeebeeTextureShader",
    "GaussRule",
    "GaussianPSF",
    "IImageWarp2D",
    "IRenderer3D",
    "ImageDef2D",
    "ImageDefOpts",
    "ImageWarpResult",
    "Light",
    "Mesh2D",
    "Mesh3D",
    "PixIntGrid2D",
    "PixIntSpeck2D",
    "PxInt2DOpts",
    "RectRule",
    "RenderCapabilities",
    "RenderInputError",
    "RenderResult",
    "Riley",
    "RileyFunctionShader",
    "RileyNodalShader",
    "RileyTextureShader",
    "Scene2D",
    "Scene3D",
    "StereoAngles",
    "StereoCameras",
    "StereoExtrinsics",
    "UVPlane",
    "UVTransform",
    "ValidationIssue",
    "average_subpixel_image",
    "blender_available",
    "blender_camera_from_resolution",
    "blender_field_of_view",
    "blender_gpu_available",
    "blender_mm_per_pixel",
    "calculate_edge_function",
    "calculate_elem_bound_box_high",
    "calculate_elem_bound_box_low",
    "calibration_image_count",
    "cam_frame_mesh",
    "cam_frame_points",
    "cam_frame_scene",
    "cam_look_at",
    "cam_pos_fill_frame",
    "cam_project_points",
    "crop_image_rectangle",
    "evenly_spaced_frame_indices",
    "first_last_frame_indices",
    "focal_length_from_resolution",
    "format_image_number",
    "image_crop",
    "image_grayscale",
    "image_load",
    "image_normalise",
    "image_resize",
    "image_save",
    "mesh2d_from_simdata",
    "mesh3d_from_simdata",
    "mesh_bounds",
    "mesh_center",
    "mesh_center_at",
    "mesh_rotate",
    "mesh_scale",
    "mesh_transform",
    "mesh_translate",
    "pixel_grid_leng",
    "pixel_vec_leng",
    "quantise_image",
    "raise_if_blender_unavailable",
    "render_calibration_images",
    "scene_arrange_circle",
    "scene_arrange_grid",
    "scene_arrange_line",
    "scene_arrange_points",
    "scene_bounds",
    "scene_center",
    "scene_rotate",
    "scene_translate",
    "select_frames",
    "subpixel_grid_leng",
    "subpixel_vec_leng",
    "stereo_build_faceon",
    "stereo_build_from_calibration",
    "stereo_build_symmetric",
    "stereo_calc_angles",
    "stereo_calc_baseline",
    "stereo_calc_extrinsics",
    "stereo_calc_stand_off",
    "stereo_save_calibration_matchid",
    "stereo_save_calibration_yaml",
    "to_riley_camera",
    "to_riley_mesh",
    "uv_from_pixels",
    "uv_project_planar",
    "uv_project_planar_centered",
    "uv_project_planar_pixels",
    "uv_to_pixels",
    "uv_transform",
]
