# ============================================================================
# pyvale: the python validation engine
# License: MIT
# Copyright (C) 2026 Sceptical Rabbit (Lloyd Fletcher)
# ============================================================================
"""The interface for 3D renderers."""

from abc import ABC, abstractmethod
from .result import RenderResult
from .scene import Scene3D


class IRenderer3D(ABC):
    """Abstract interface for 3D renderers.

    The public :meth:`render` method always validates a concrete scene before
    the backend may allocate image buffers or start rendering.
    """

    def render(
        self,
        scene: Scene3D,
    ) -> RenderResult:
        """Validate and render a three-dimensional scene.

        Parameters
        ----------
        scene : Scene3D
            Complete rendering request.

        Returns
        -------
        RenderResult
            Images and optional output paths produced by the backend.

        Raises
        ------
        RenderInputError
            If the scene is not supported or contains invalid data.
        """
        self.verify_input(scene)
        return self._render(scene)

    @abstractmethod
    def verify_input(
        self,
        scene: Scene3D,
    ) -> None:
        """Validate a render request without expensive preparation.

        Parameters
        ----------
        scene : Scene3D
            Complete rendering request to validate.

        Raises
        ------
        RenderInputError
            If the request is invalid or unavailable in this backend.
        """

    @abstractmethod
    def _render(self, scene: Scene3D) -> RenderResult:
        """Render a backend plan that has already passed validation.

        Parameters
        ----------
        scene : Scene3D
            Previously validated rendering request.

        Returns
        -------
        RenderResult
            Images and optional output paths generated by the backend.
        """


__all__ = ["IRenderer3D"]
