# ============================================================================
# pyvale: the python validation engine
# License: MIT
# Copyright (C) 2026 Sceptical Rabbit (Lloyd Fletcher)
# ============================================================================
"""The interface for 3D renderers."""

from abc import ABC, abstractmethod
from collections.abc import Sequence

from .camera import Camera
from .light import Light
from .mesh import Mesh
from .result import RenderResult


class IRenderer3D(ABC):
    """Abstract interface for 3D renderers.

    Concrete renderers implement :meth:`verify_input` and :meth:`_render`.
    The public :meth:`render` method always validates a request before the
    backend may create a scene, allocate image buffers, or start rendering.
    """

    def render(
        self,
        meshes: Sequence[Mesh],
        cameras: Sequence[Camera],
        lights: Sequence[Light] | None = None,
    ) -> RenderResult:
        """Validate and render a three-dimensional scene.

        Parameters
        ----------
        meshes : Sequence[Mesh]
            Surface meshes to render.
        cameras : Sequence[Camera]
            Cameras from which to render the scene.
        lights : Sequence[Light] or None, optional
            Scene lights. ``None`` requests the backend default lighting.

        Returns
        -------
        RenderResult
            Images and optional output paths produced by the backend.

        Raises
        ------
        RenderInputError
            If the scene is not supported or contains invalid data.
        """
        render_plan = self.verify_input(meshes, cameras, lights)
        return self._render(render_plan)

    @abstractmethod
    def verify_input(
        self,
        meshes: Sequence[Mesh],
        cameras: Sequence[Camera],
        lights: Sequence[Light] | None = None,
    ) -> object:
        """Validate a render request without expensive preparation.

        Parameters
        ----------
        meshes : Sequence[Mesh]
            Surface meshes to validate.
        cameras : Sequence[Camera]
            Cameras to validate.
        lights : Sequence[Light] or None, optional
            Lights to validate.

        Returns
        -------
        object
            An opaque, backend-specific plan consumed by :meth:`_render`.

        Raises
        ------
        RenderInputError
            If the request is invalid or unavailable in this backend.
        """

    @abstractmethod
    def _render(self, render_plan: object) -> RenderResult:
        """Render a backend plan that has already passed validation.

        Parameters
        ----------
        render_plan : object
            Backend-specific plan returned by :meth:`verify_input`.

        Returns
        -------
        RenderResult
            Images and optional output paths generated by the backend.
        """


__all__ = ["IRenderer3D"]
