#===============================================================================
# pyvale: the python validation engine
# License: MIT
# Copyright (C) 2025 The Computer Aided Validation Team
#===============================================================================

from pathlib import Path
import pytest
import shutil
from pyvale.mooseherder.gmshrunner import GmshRunner

GMSH_INPUT_PATH = Path.cwd()/"tests"/"mooseherder"/"gmsh"

def test_gmsh_exists(gmsh_path: Path):
    assert gmsh_path.is_file()


@pytest.fixture()
def gmsh_path() -> Path:
    path = shutil.which("gmsh")
    if path is None:
        pytest.skip("Gmsh is not installed or available on PATH")
    return Path(path)


@pytest.fixture()
def runner(gmsh_path: Path) -> GmshRunner:
    return GmshRunner(gmsh_path)


@pytest.fixture()
def input_file() -> Path:
    return GMSH_INPUT_PATH/"gmsh-test.geo"


@pytest.fixture(autouse=True)
def setup_teardown():
    # Setup here
    yield
    # Teardown here - remove output files
    for output_file in GMSH_INPUT_PATH.glob("*.msh"):
        output_file.unlink()

def test_create_runner(runner: GmshRunner, gmsh_path: Path) -> None:
    assert runner._gmsh_app == gmsh_path


def test_create_runner_err() -> None:
    wrong_path = Path("/nonexistent/gmsh")
    with pytest.raises(FileNotFoundError) as err_info:
        _ = GmshRunner(wrong_path)

    msg, = err_info.value.args
    assert msg == 'Gmsh app not found at given path.'

def test_set_gmsh_app(gmsh_path: Path) -> None:
    check_runner = GmshRunner()
    check_runner.set_gmsh_app(gmsh_path)
    assert check_runner._gmsh_app == gmsh_path


def test_set_gmsh_app_err() -> None:
    wrong_path = Path("/nonexistent/gmsh")
    with pytest.raises(FileNotFoundError) as err_info:
        check_runner = GmshRunner()
        check_runner.set_gmsh_app(wrong_path)

    msg, = err_info.value.args
    assert msg == 'Gmsh app not found at given path.'


def test_set_input_file(runner: GmshRunner, input_file: Path) -> None:
    runner.set_input_file(input_file)
    assert runner.get_input_file() == input_file


def test_set_input_err_geo(runner: GmshRunner) -> None:
    wrong_file = GMSH_INPUT_PATH/"gmsh-test.i"
    with pytest.raises(FileNotFoundError) as err_info:
        runner.set_input_file(wrong_file)
    msg, = err_info.value.args
    assert msg == 'Incorrect file type. Must be *.geo.'


def test_set_input_err_exist(runner: GmshRunner) -> None:
    wrong_file = GMSH_INPUT_PATH/"gmsh-test-noexist.geo"
    with pytest.raises(FileNotFoundError) as err_info:
        runner.set_input_file(wrong_file)
    msg, = err_info.value.args
    assert msg == 'Specified gmsh geo file does not exist.'


def test_run(runner: GmshRunner, input_file: Path) -> None:
    runner.set_input_file(input_file)
    runner.run()
    assert (GMSH_INPUT_PATH/"gmsh-test.msh").is_file(), 'Output mesh *.msh file not generated by gmsh.'


def test_run_with_input(runner: GmshRunner, input_file: Path) -> None:
    runner.run(input_file)
    assert (GMSH_INPUT_PATH/"gmsh-test.msh").is_file(), 'Output mesh *.msh file not generated by gmsh.'


def test_run_err_no_gmsh(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        "pyvale.mooseherder.availability.shutil.which",
        lambda _: None,
    )
    check_runner = GmshRunner()
    with pytest.raises(RuntimeError) as err_info:
        check_runner.run()
    msg, = err_info.value.args
    assert msg == "Gmsh was not found on PATH. Install Gmsh or configure its path."


def test_run_err_no_geo(runner: GmshRunner) -> None:
    with pytest.raises(RuntimeError) as err_info:
        runner.run()
    msg, = err_info.value.args
    assert msg == "Specify input *.geo file before running gmsh."
