# ==============================================================================
# pyvale: the python validation engine
# License: MIT
# Copyright (C) 2025 The Computer Aided Validation Team
# ==============================================================================

"""Numerical MAVM regression cases ported from fullfieldvalmetrics.

The input constructions match ``scripts/test_mavm_analytic.py`` from
fullfieldvalmetrics. Expected results were generated by its corrected
``scripts/valmetrics.py:mavm`` implementation. Test 08 uses a fixed legacy
NumPy random seed because the source script leaves its random input unseeded.
"""

import numpy as np
import pytest

from pyvale.valid.metrics import calc_mavm_1d, calc_mavm_pbox_1d


def _reference_cases() -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Build the eight analytic input cases from fullfieldvalmetrics."""
    cases: dict[str, tuple[np.ndarray, np.ndarray]] = {}

    num_exp = 4
    num_sim = 2
    exp_data = np.arange(num_exp, dtype=np.float64) - num_exp / 2.0
    sim_data = exp_data[num_exp - num_sim :] + exp_data[-1] + 1.0
    cases["test01"] = (sim_data, exp_data)

    num_exp = 2
    num_sim = 4
    sim_data = np.arange(num_sim, dtype=np.float64) - num_sim / 2.0
    exp_data = sim_data[num_sim - num_exp :] + sim_data[-1] + 2.0
    cases["test02"] = (sim_data, exp_data)

    num_exp = 4
    num_sim = 2
    exp_data = np.arange(num_exp, dtype=np.float64) - num_exp / 2.0
    sim_data = np.arange(num_sim, dtype=np.float64) - num_sim / 2.0
    cases["test03"] = (sim_data, exp_data)

    num_exp = 4
    num_sim = 3
    exp_data = np.arange(num_exp, dtype=np.float64) - num_exp / 2.0
    sim_data = exp_data[num_exp - num_sim :] + exp_data[-1] + 1.0
    cases["test04"] = (sim_data, exp_data)

    num_exp = 3
    num_sim = 4
    sim_data = np.arange(num_sim, dtype=np.float64) - num_sim / 2.0
    exp_data = sim_data[num_sim - num_exp :] + sim_data[-1] + 2.0
    cases["test05"] = (sim_data, exp_data)

    num_exp = 4
    num_sim = 3
    exp_data = np.arange(num_exp, dtype=np.float64) - num_exp / 2.0
    sim_data = np.arange(num_sim, dtype=np.float64) - num_sim / 2.0
    cases["test06"] = (sim_data, exp_data)

    num_exp = 100
    num_sim = 10_000
    offset = num_sim
    exp_data = np.arange(num_exp, dtype=np.float64) - num_exp / 2.0
    exp_data += 1.25 * offset
    sim_data = np.arange(num_sim, dtype=np.float64) - num_sim / 2.0 + offset
    cases["test07"] = (sim_data, exp_data)

    np.random.seed(2025)
    exp_data = np.random.uniform(low=230.95, high=237.16, size=25)
    exp_data = np.repeat(exp_data, 4)
    sim_data = np.random.normal(loc=238.0, scale=4.0, size=10_000)
    cases["test08"] = (sim_data, exp_data)

    return cases


@pytest.mark.parametrize(
    ("case_name", "expected_d_plus", "expected_d_minus"),
    [
        ("test01", 0.0, 4.315570153994818),
        ("test02", 6.232248255376777, 0.0),
        ("test03", 1.315570153994818, 1.315570153994818),
        ("test04", 0.0, 3.815570153994818),
        ("test05", 4.87649440322337, 0.0),
        ("test06", 1.315570153994818, 1.315570153994818),
        ("test07", 2806.765551246437, 304.34465910224606),
        ("test08", 0.11251308444727751, 4.317398787045127),
    ],
)
def test_mavm_matches_fullfield_analytic_cases(
    case_name: str,
    expected_d_plus: float,
    expected_d_minus: float,
) -> None:
    """Match fullfieldvalmetrics MAVM values to floating-point tolerance."""
    model_data, exp_data = _reference_cases()[case_name]

    result = calc_mavm_1d(model_data, exp_data)

    assert result.d_plus == pytest.approx(expected_d_plus, abs=1e-10)
    assert result.d_minus == pytest.approx(expected_d_minus, abs=1e-10)
    assert result.d_total == pytest.approx(
        expected_d_plus + expected_d_minus,
        abs=1e-10,
    )


def test_mavm_pbox() -> None:
    """Epistemic p-box calculation evaluates outer envelope bounds."""
    rng = np.random.default_rng(123)
    exp_data = rng.normal(loc=50.0, scale=2.0, size=100)
    sim_min = rng.normal(loc=45.0, scale=2.0, size=200)
    sim_max = rng.normal(loc=55.0, scale=2.0, size=200)

    result = calc_mavm_pbox_1d(sim_min, sim_max, exp_data, alpha=0.05)

    assert result.d_plus > 0.0
    assert result.d_minus > 0.0
    assert result.d_total == result.d_plus + result.d_minus


def _rectangle_signed_areas(
    model_quantiles: np.ndarray,
    model_probs: np.ndarray,
    exp_quantiles: np.ndarray,
    exp_probs: np.ndarray,
) -> tuple[float, float]:
    """Integrate quantile-function differences as finite rectangles.

    Merging the two empirical-CDF probability grids gives a direct,
    independent area calculation for the MAVM integration loop.
    """
    model_index = 0
    exp_index = 0
    prob = 0.0
    d_plus = 0.0
    d_minus = 0.0
    while model_index < len(model_quantiles) and exp_index < len(exp_quantiles):
        next_prob = min(
            model_probs[model_index],
            exp_probs[exp_index],
        )
        area = (exp_quantiles[exp_index] - model_quantiles[model_index]) * (
            next_prob - prob
        )
        if area > 0.0:
            d_plus += area
        else:
            d_minus -= area

        prob = next_prob
        if np.isclose(prob, model_probs[model_index]):
            model_index += 1
        if np.isclose(prob, exp_probs[exp_index]):
            exp_index += 1

    return d_plus, d_minus


def _rectangle_mavm_areas(
    model_data: np.ndarray,
    exp_data: np.ndarray,
    alpha: float = 0.05,
) -> tuple[float, float]:
    """Calculate MAVM using only merged empirical-CDF rectangles."""
    from scipy import stats

    model_cdf = stats.ecdf(model_data).cdf
    exp_cdf = stats.ecdf(exp_data).cdf
    model_quantiles = model_cdf.quantiles
    model_probs = model_cdf.probabilities
    exp_quantiles = exp_cdf.quantiles
    exp_probs = exp_cdf.probabilities
    t_value = stats.t.ppf(1.0 - alpha, len(exp_quantiles) - 1)
    standard_error = np.std(exp_quantiles) / np.sqrt(len(exp_quantiles))

    lower = _rectangle_signed_areas(
        model_quantiles,
        model_probs,
        exp_quantiles - t_value * standard_error,
        exp_probs,
    )
    upper = _rectangle_signed_areas(
        model_quantiles,
        model_probs,
        exp_quantiles + t_value * standard_error,
        exp_probs,
    )
    return max(lower[0], upper[0]), max(lower[1], upper[1])


@pytest.mark.parametrize(
    ("model_data", "exp_data"),
    [
        (np.array([0.0, 2.0]), np.array([0.0, 2.0])),
        (np.array([2.0, 4.0]), np.array([0.0, 2.0])),
        (np.array([0.0, 2.0]), np.array([2.0, 4.0])),
        (np.array([0.0, 4.0]), np.array([1.0, 2.0, 3.0])),
        (np.array([0.0, 2.0, 4.0]), np.array([1.0, 3.0])),
        (np.array([0.0, 0.0, 2.0]), np.array([1.0, 1.0, 3.0, 3.0])),
        (np.array([0.0, 0.0, 2.0]), np.array([1.0, 3.0, 3.0, 3.0])),
        (np.array([0.0, 2.0, 4.0, 6.0, 8.0]), np.array([1.0, 5.0, 9.0])),
    ],
)
def test_mavm_matches_independent_rectangle_integration(
    model_data: np.ndarray,
    exp_data: np.ndarray,
) -> None:
    """Cover odd/even, unequal-size, and repeated-value ECDF cases."""
    expected_d_plus, expected_d_minus = _rectangle_mavm_areas(
        model_data,
        exp_data,
    )

    result = calc_mavm_1d(model_data, exp_data)

    assert result.d_plus == pytest.approx(expected_d_plus, abs=1e-12)
    assert result.d_minus == pytest.approx(expected_d_minus, abs=1e-12)


@pytest.mark.parametrize(
    ("model_data", "exp_data", "expected_area"),
    [
        (np.array([-1.0, 1.0]), np.array([-1.0, 1.0]), 0.0),
        (np.array([1.0, 3.0]), np.array([0.0, 2.0]), 1.0),
        (np.array([0.0, 4.0]), np.array([1.0, 2.0, 3.0]), 4.0 / 3.0),
        (np.array([0.0, 2.0, 4.0]), np.array([1.0, 3.0]), 1.0),
        (
            np.array([0.0, 0.0, 2.0]),
            np.array([1.0, 3.0, 3.0, 3.0]),
            11.0 / 6.0,
        ),
    ],
)
def test_avm_matches_hand_calculated_ecdf_rectangles(
    model_data: np.ndarray,
    exp_data: np.ndarray,
    expected_area: float,
) -> None:
    """Verify AVM against manually summed empirical-CDF rectangles."""
    from pyvale.valid.metrics import calc_avm_1d

    assert calc_avm_1d(model_data, exp_data) == pytest.approx(
        expected_area,
        abs=1e-12,
    )
