from __future__ import annotations

"""Regression tests for the slice-wise force metric and identification flow.

The fixture is a deterministic rectangular tensile case generated by
`tests/vfm/slicewise_validation_case.py`. The raw files mimic the Ansys text
exports that will eventually be replaced by a real FE solve; the prepared data
are produced through the normal `process_input_data` path so these tests use
the same input convention as production VFM workflows.
"""

import numpy as np
import numpy.testing as npt
import pytest

from pyvale.vfm.constlaws import IsotropicVonMisesElastoplasticity
from pyvale.vfm.experimentdata import ExperimentData
from pyvale.vfm.hardening import HardeningLinear
from pyvale.vfm.identification import run_identification
from pyvale.vfm.identificationconfig import IdentificationConfig, IdentificationPhase
from pyvale.vfm.metricsliceforce import SliceWiseForceReconstructionMetric
from pyvale.vfm.objectivefuncvector import VectorWeightedObjective
from pyvale.vfm.optimiserslicewiseindependent import SliceWiseIndependentLeastSquares
from pyvale.vfm.refinement import SliceMergeSplitRefinement
from slicewise_validation_case import (
    PARAMETER_MAP_NAMES,
    SlicewiseValidationProcessedCase,
    ensure_rectangle_slicewise_yield_case,
    make_identification_parameters,
)
from pyvale.vfm.slicewise_utils import SliceConfig
from pyvale.vfm.spatialparamknown import SpatialParameterisationKnown
from pyvale.vfm.spatialparamslicewise import (
    SliceWiseSpatialParameterisation,
    SupportSlice,
)


YIELD_STRENGTH_ATOL = 1.0e-3
FORCE_ATOL = 1.0e-5
IDENTIFIED_FRE_RTOL = 1.0e-7
IDENTIFIED_FORCE_ATOL = 1.0e-3


@pytest.fixture(scope="module")
def slicewise_case() -> SlicewiseValidationProcessedCase:
    """Load or generate the canonical external rectangle slice-wise fixture."""

    return ensure_rectangle_slicewise_yield_case()


def test_slicewise_fre_is_zero_for_known_yield_distribution(
    slicewise_case: SlicewiseValidationProcessedCase,
) -> None:
    """Known maps should reconstruct the applied force in every slice.

    The synthetic strain history is generated so that every material slice
    reconstructs the same target x-stress at every load step. The area-based
    force metric should therefore return numerical zero for the noiseless
    fixture.
    """

    experiment_data = ExperimentData.load_from_file(slicewise_case.experiment_data_file)
    constitutive_law = IsotropicVonMisesElastoplasticity(HardeningLinear())
    known_maps, expected_boundaries = _load_known_maps_and_boundaries(slicewise_case)
    stress = constitutive_law.calculate_stress(experiment_data.strain, known_maps)

    metric = SliceWiseForceReconstructionMetric(
        slice_config=SliceConfig(axis="x", num_slices=4),
    )
    metric.initialise(experiment_data)
    assert metric.slice_partition is not None
    npt.assert_allclose(
        metric.slice_partition.boundaries,
        expected_boundaries,
        rtol=0.0,
        atol=1.0e-10,
    )

    fre = metric.evaluate_force_recon_error(stress, experiment_data)
    applied_force = fre.metric_result.additional_fields["applied_longitudinal_force"]

    npt.assert_allclose(
        fre.metric_result.additional_fields["reconstructed_force"],
        np.broadcast_to(
            applied_force[:, np.newaxis],
            fre.metric_result.additional_fields["reconstructed_force"].shape,
        ),
        rtol=1.0e-10,
        atol=FORCE_ATOL,
    )
    assert fre.weighted_spatiotemporal_rms < 1.0e-8


def test_explicit_geometric_boundaries_are_cell_aligned_by_default(
    slicewise_case: SlicewiseValidationProcessedCase,
) -> None:
    """Explicit boundaries are intended geometry and are snapped to cells."""

    experiment_data = ExperimentData.load_from_file(slicewise_case.experiment_data_file)
    expected_maps, expected_boundaries = _load_known_maps_and_boundaries(slicewise_case)
    intended_boundaries = np.linspace(
        float(np.nanmin(experiment_data.specimen_geometry.x)),
        float(np.nanmax(experiment_data.specimen_geometry.x)),
        expected_boundaries.size,
    )

    metric = SliceWiseForceReconstructionMetric(
        slice_config=SliceConfig(axis="x", boundaries=intended_boundaries),
    )
    metric.initialise(experiment_data)
    assert metric.slice_partition is not None
    npt.assert_allclose(
        metric.slice_partition.boundaries,
        expected_boundaries,
        rtol=0.0,
        atol=1.0e-10,
    )

    constitutive_law = IsotropicVonMisesElastoplasticity(HardeningLinear())
    stress = constitutive_law.calculate_stress(experiment_data.strain, expected_maps)
    fre = metric.evaluate_force_recon_error(stress, experiment_data)
    assert fre.weighted_spatiotemporal_rms < 1.0e-8


def test_slicewise_identification_recovers_four_slice_yield_distribution(
    slicewise_case: SlicewiseValidationProcessedCase,
) -> None:
    """Four x-slices should identify the four known yield strengths."""

    experiment_data = ExperimentData.load_from_file(slicewise_case.experiment_data_file)
    expected_maps, _ = _load_known_maps_and_boundaries(slicewise_case)
    result = _run_yield_identification(
        experiment_data,
        slice_config=SliceConfig(axis="x", num_slices=4),
    )

    npt.assert_allclose(
        result.parameter_maps["yield_strength"],
        expected_maps["yield_strength"],
        rtol=0.0,
        atol=YIELD_STRENGTH_ATOL,
    )
    _assert_fre_zero_for_parameter_maps(
        experiment_data,
        result.parameter_maps,
        SliceConfig(axis="x", num_slices=4),
    )


def test_slicewise_identification_recovers_columnwise_distribution(
    slicewise_case: SlicewiseValidationProcessedCase,
) -> None:
    """A one-slice-per-column support should recover the same step map.

    This checks the high-resolution limit of the slice-wise support. Because
    the support is snapped to support-cell edges, every datapoint cell has one
    material owner and can be checked pointwise.
    """

    experiment_data = ExperimentData.load_from_file(slicewise_case.experiment_data_file)
    num_columns = experiment_data.specimen_geometry.x.shape[1]
    result = _run_yield_identification(
        experiment_data,
        slice_config=SliceConfig(axis="x", num_slices=num_columns),
    )
    expected_maps, _ = _load_known_maps_and_boundaries(slicewise_case)

    npt.assert_allclose(
        result.parameter_maps["yield_strength"],
        expected_maps["yield_strength"],
        rtol=0.0,
        atol=YIELD_STRENGTH_ATOL,
    )


def test_slicewise_identification_with_refinement_recovers_expected_distribution(
    slicewise_case: SlicewiseValidationProcessedCase,
) -> None:
    """An over-refined eight-slice support should merge back to four slices."""

    experiment_data = ExperimentData.load_from_file(slicewise_case.experiment_data_file)
    expected_maps, expected_boundaries = _load_known_maps_and_boundaries(slicewise_case)
    result = _run_yield_identification(
        experiment_data,
        slice_config=SliceConfig(axis="x", num_slices=8),
        refinement_policy=True,
    )

    npt.assert_allclose(
        result.parameter_maps["yield_strength"],
        expected_maps["yield_strength"],
        rtol=0.0,
        atol=YIELD_STRENGTH_ATOL,
    )

    snapshot = result.history.phases[-1].spatial_parameterisations["yield_strength"][0]
    refined_parameterisation = snapshot.parameterisation
    assert isinstance(refined_parameterisation, SliceWiseSpatialParameterisation)
    assert refined_parameterisation.slice_partition is not None
    assert refined_parameterisation.slice_partition.num_slices == 4
    npt.assert_allclose(
        refined_parameterisation.slice_partition.boundaries,
        expected_boundaries,
        rtol=0.0,
        atol=1.0e-10,
    )


def _run_yield_identification(
    experiment_data: ExperimentData,
    *,
    slice_config: SliceConfig,
    refinement_policy: bool = False,
):
    """Run one phase of yield-strength identification on fixed E/nu/H maps."""

    constitutive_law = IsotropicVonMisesElastoplasticity(HardeningLinear())
    parameter_map_size = np.asarray(
        experiment_data.specimen_geometry.x.shape,
        dtype=np.uint32,
    )
    shared_support = SupportSlice(
        slice_config=slice_config,
    )

    phase = IdentificationPhase(
        spatial_parameterisations={
            "elastic_modulus": [SpatialParameterisationKnown()],
            "poissons_ratio": [SpatialParameterisationKnown()],
            "yield_strength": [SliceWiseSpatialParameterisation(support=shared_support)],
            "hardening_modulus": [SpatialParameterisationKnown()],
        },
        metrics=[SliceWiseForceReconstructionMetric(support=shared_support)],
        objective_function=VectorWeightedObjective(),
        optimiser=SliceWiseIndependentLeastSquares(),
        refinement_policy=(
            SliceMergeSplitRefinement(
                target=shared_support,
                merge_parameter_tolerance=0.04,
                split_error_threshold=1.0,
                max_refinements=1,
            )
            if refinement_policy
            else None
        ),
    )

    return run_identification(
        experiment_data,
        IdentificationConfig(
            constitutive_law=constitutive_law,
            parameters=make_identification_parameters(parameter_map_size),
            phases=[phase],
        ),
    )


def _load_known_maps_and_boundaries(
    slicewise_case: SlicewiseValidationProcessedCase,
) -> tuple[dict[str, np.ndarray], np.ndarray]:
    with np.load(slicewise_case.known_parameter_maps_file) as loaded:
        known_maps = {
            name: np.asarray(loaded[name], dtype=np.float64)
            for name in PARAMETER_MAP_NAMES
        }
        slice_boundaries = np.asarray(loaded["slice_boundaries"], dtype=np.float64)
    return known_maps, slice_boundaries


def _assert_fre_zero_for_parameter_maps(
    experiment_data: ExperimentData,
    parameter_maps: dict[str, np.ndarray],
    slice_config: SliceConfig,
) -> None:
    constitutive_law = IsotropicVonMisesElastoplasticity(HardeningLinear())
    stress = constitutive_law.calculate_stress(experiment_data.strain, parameter_maps)
    metric = SliceWiseForceReconstructionMetric(
        slice_config=slice_config,
    )
    metric.initialise(experiment_data)
    fre = metric.evaluate_force_recon_error(stress, experiment_data)
    raw_residual = fre.metric_result.additional_fields["raw_residual"]
    assert fre.weighted_spatiotemporal_rms < IDENTIFIED_FRE_RTOL
    assert np.nanmax(np.abs(raw_residual)) < IDENTIFIED_FORCE_ATOL
