#!/usr/bin/env bash
set -e
set -o pipefail

echo "=========================================="
echo " GENERATING PYTHON API DOCUMENTATION..."
echo "=========================================="

# Function to handle errors
error_exit() {
    echo "ERROR: $1"
    exit 1
}

# Python API documentation
sphinx-apidoc -f -o ./source --separate ../src/pyvale/ ../src/pyvale/data/* ../src/pyvale/examples/* || error_exit "sphinx-apidoc failed"

# Remove autogenerated TOC file
rm -f source/modules.rst || error_exit "Failed to remove modules.rst"

echo "Updating generated RST files..."

# Modules to process
modules=("dic" "blender" "mooseherder" "sensorsim" "verif" "dataset" "strain" "specklegen")

for mod in "${modules[@]}"; do
    rst="source/pyvale.${mod}.rst"

    # Remove redundant headers
    sed -i '/^pyvale package$/,+1d; /^Submodules$/,+1d' "$rst" || error_exit "Failed removing headers in $rst"

    # Add caption
    sed -i '/^\.\. toctree::/a \   :caption: Python Source Files' "$rst" || error_exit "Failed adding caption in $rst"

    # Remove "package" word
    sed -i 's/package//g' "$rst" || error_exit "Failed removing 'package' in $rst"

    # Remove 'Module contents' section
    sed -i '/^Module contents$/,/^ *:undoc-members:/d' "$rst" || error_exit "Failed trimming module contents in $rst"

    # Change toctree level from 4 to 1
    sed -i 's/4/1/g' "$rst" || error_exit "Failed updating toctree level in $rst"

    sed -i "0,/\\b${mod}\.\([a-zA-Z0-9_]\+\)/s//\1.py/" source/pyvale.${mod}.*.rst || error_exit "Failed replacing '${mod}.*' with '*.py' in $rst"

done

# Tweak module titles across all rst files
sed -i 's/^pyvale\.\(.*\) module$/\1/' source/pyvale.*.rst || error_exit "Failed fixing module titles"

# Remove unneeded file
rm -f ./source/pyvale.dic.dic2dcpp.rst || error_exit "Failed to remove dic2dcpp.rst"

echo "PYTHON API DOCUMENTATION GENERATED SUCCESSFULLY!"

# ------------------------------------------------------------------
# Generate C++ API documentation
# ------------------------------------------------------------------
echo "=========================================="
echo " GENERATING C++ API DOCUMENTATION..."
echo "=========================================="

# Run Doxygen (optional, if you still want it)
( cd ./source && doxygen Doxyfile ) || error_exit "doxygen generation failed"

# Create RST files for each C++ header
for mod in "${modules[@]}"; do
    src_dir="../src/pyvale/${mod}/cpp"
    out_dir="source/cpp/${mod}"

    mkdir -p "$out_dir"

    for file in "$src_dir"/*.hpp; do
        [ -e "$file" ] || continue

        filename=$(basename "$file")
        base="${filename%.hpp}"
        rst_file="${out_dir}/${base}.rst"

        echo "Generating $rst_file"

        cat > "$rst_file" <<EOF
${filename}
==================

.. doxygenfile:: ${filename}
   :project: pyvale
   :path: ${src_dir}
EOF
    done
done

# ------------------------------------------------------------------
# Generate module-level index RST files for C++ headers
# ------------------------------------------------------------------
for mod in "${modules[@]}"; do
    out_dir="source/cpp/${mod}"
    index_file="source/cpp/cpp_${mod}.rst"

    headers=""
    for f in "$out_dir"/*.rst; do
        [ -e "$f" ] || continue  # skip if no files
        headers="$headers $(basename "$f")"
    done

    # Skip if no headers found
    [ -z "$headers" ] && continue

    # Sort headers alphabetically
    headers=$(echo $headers | tr ' ' '\n' | sort)

    echo "Generating module index $index_file"

    {
        echo "${mod}"
        echo "=================="
        echo ""
        echo ".. toctree::"
        echo "   :caption: C++ Source Files"
        echo "   :maxdepth: 1"
        echo ""
        for h in $headers; do
            echo "   ${mod}/${h}"
        done
    } > "$index_file"
done



echo "C++ RST FILES GENERATED SUCCESSFULLY!"

