echo "=========================================="
echo " GENERATING PYTHON API DOCUMENTATION..."
echo "=========================================="
#generate the python api documentation
sphinx-apidoc -f -o ./source --separate ../src/pyvale/ ../src/pyvale/data/* ../src/pyvale/examples/ --tocfile api_py

if [ $? -ne 0 ]; then
    echo "... sphinx-apidoc failed!"
    exit 1
fi

echo "Updating generated RST files..."

# change autogenerated title
sed -i 's/^pyvale$/Detailed Python API/' source/api_py.rst

# make sure title is long enough for the 'detailed python api' page.
sed -i 's/=/====/g' source/api_py.rst

# Remove redundant headers generated by sphinx-apidoc
sed -i '/^pyvale package$/,+1d; /^Submodules$/,+1d' source/pyvale.rst

# remove any reference to 'module' in the headers for detailed python api page
sed -i 's/^pyvale\.\(.*\) module$/\1/' source/pyvale.*.rst

# remove module contents and anything below in source/pyvale.rst otherwise we
# get a pointless page in the detailed python API docs
sed -i '/^Module contents$/,/^ *:undoc-members:/d' source/pyvale.rst

# Remove the dic2dcpp file. This is not needed for the python detailed api
# documentation
rm ./source/pyvale.dic2dcpp.rst


echo "PYTHON API DOCUMENTATION GENERATED SUCCESSFULLY!"


