name: Build Wheels and upload (if new release) to PyPI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-14, macos-15-intel, macos-latest]
        include:
          - os: macos-14
            llvm: llvm@15
            macos_deployment_target: "14.0"
          - os: macos-15-intel
            llvm: llvm@18
            macos_deployment_target: "15.0"
          - os: macos-latest
            llvm: llvm@18
            macos_deployment_target: "15.0"
    steps:
      - uses: actions/checkout@v4

      - name: Set compiler on macOS to GCC
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install libomp
          echo "MACOSX_DEPLOYMENT_TARGET=${{ matrix.macos_deployment_target }}" >> $GITHUB_ENV
          echo "CC=gcc-15" >> $GITHUB_ENV
          echo "CXX=g++-15" >> $GITHUB_ENV

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libegl1 libgl1 libxext6 libx11-6
          sudo apt install -y gcc-13 g++-13 || sudo apt install -y gcc-12 g++-12 || sudo apt install -y gcc-10 g++-10
          GCC_BIN=$(command -v gcc-13 || command -v gcc-12 || command -v gcc-10 || command -v gcc)
          GXX_BIN=$(command -v g++-13 || command -v g++-12 || command -v g++-10 || command -v g++)
          echo "CC=$GCC_BIN" >> $GITHUB_ENV
          echo "CXX=$GXX_BIN" >> $GITHUB_ENV
          echo "CMAKE_C_COMPILER=$GCC_BIN" >> $GITHUB_ENV
          echo "CMAKE_CXX_COMPILER=$GXX_BIN" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"
        env:
          CIBW_SKIP: "pp*"
          CIBW_ENVIRONMENT_LINUX: >
            CC=/usr/bin/gcc-13
            CXX=/usr/bin/g++-13
            CMAKE_C_COMPILER=/usr/bin/gcc-13
            CMAKE_CXX_COMPILER=/usr/bin/g++-13

      - uses: actions/upload-artifact@v4
        with:
          name: pyvale-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: pyvale-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: pyvale-*
          path: dist
          merge-multiple: true

      # upload to pypi
      - uses: pypa/gh-action-pypi-publish@release/v1
        #with:
        #  repository-url: https://test.pypi.org/legacy/
