name: Build Wheels and upload (if new release) to PyPI

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  release:
    types:
      - published
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-14, macos-15-intel, macos-latest]
        include:
          - os: macos-14
            llvm: llvm@15
          - os: macos-15-intel
            llvm: llvm@18
          - os: macos-latest
            llvm: llvm@18
    steps:
      - uses: actions/checkout@v4

      - name: Install libomp and set compiler on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install libomp
          echo "CC=$(brew --prefix ${{ matrix.llvm }})/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix ${{ matrix.llvm }})/bin/clang++" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix libomp)/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix libomp)/include" >> $GITHUB_ENV
          echo "OpenMP_ROOT=$(brew --prefix libomp)" >> $GITHUB_ENV
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"
        # env:
        #   CIBW_SKIP: "pp*"
        #   CIBW_ENVIRONMENT_MACOS: >
        #     CC=$(brew --prefix ${{ matrix.llvm }})/bin/clang
        #     CXX=$(brew --prefix ${{ matrix.llvm }})/bin/clang++
        #     LDFLAGS="-L$(brew --prefix libomp)/lib"
        #     CPPFLAGS="-I$(brew --prefix libomp)/include"
        #     OpenMP_ROOT=$(brew --prefix libomp)
      - uses: actions/upload-artifact@v4
        with:
          name: pyvale-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: pyvale-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: pyvale-*
          path: dist
          merge-multiple: true

      # upload to pypi
      - uses: pypa/gh-action-pypi-publish@release/v1
        #with:
        #  repository-url: https://test.pypi.org/legacy/
